### ISSUE TITLE
[Bug] Changing gamemodes

### ISSUE THREAD

**Issue by UltraFaceguy** [Amunak/FlyWithFood#1]
When changing gamemodes, if you have fly.force you can sometimes get stuck in a state why flt is enabled for creative mode, but does not become re-enabled upon returning to survival. Only really an issue if you're trying to do things command-less like myself, but worth looking into

**Comment by Amunak** [comment]
I have a check there for the creative mode, so this is likely a little different issue.I suspect that the fly.force permission doesn't check always. Thanks for the report.
